export const emojiCategories = [
  {
    name: "smileys",
    emojis: [
      "😀",
      "😃",
      "😄",
      "😁",
      "😆",
      "😅",
      "😂",
      "🤣",
      "😊",
      "😇",
      "🙂",
      "🙃",
      "😉",
      "😌",
      "😍",
      "🥰",
      "😘",
      "😗",
      "😙",
      "😚",
      "😋",
      "😛",
      "😝",
      "😜",
      "🤪",
      "🤨",
      "🧐",
      "🤓",
      "😎",
      "🤩",
      "🥳",
      "😏",
      "😒",
      "😞",
      "😔",
      "😟",
      "😕",
      "🙁",
      "☹️",
      "😣",
      "😖",
      "😫",
      "😩",
      "🥺",
      "😢",
      "😭",
      "😤",
      "😠",
      "😡",
      "🤬",
      "🤯",
      "😳",
      "🥵",
      "🥶",
      "😱",
      "😨",
      "😰",
      "😥",
      "😓",
      "🤗",
      "🤔",
      "🤭",
      "🤫",
      "🤥",
      "😶",
      "😐",
      "😑",
      "😬",
      "🙄",
      "😯",
      "😦",
      "😧",
      "😮",
      "😲",
      "🥱",
      "😴",
      "🤤",
      "😪",
      "😵",
      "🤐",
      "🥴",
      "🤢",
      "🤮",
      "🤧",
      "😷",
      "🤒",
      "🤕",
      "🤑",
      "🤠",
      "😈",
      "👿",
      "👹",
      "👺",
      "🤡",
      "💩",
      "👻",
      "💀",
      "☠️",
      "👽",
      "👾",
      "🤖",
      "🎃",
      "😺",
      "😸",
      "😹",
      "😻",
      "😼",
      "😽",
      "🙀",
      "😿",
      "😾",
    ],
  },
  {
    name: "gestures",
    emojis: [
      "👋",
      "🤚",
      "🖐️",
      "✋",
      "🖖",
      "👌",
      "🤌",
      "🤏",
      "✌️",
      "🤞",
      "🤟",
      "🤘",
      "🤙",
      "👈",
      "👉",
      "👆",
      "🖕",
      "👇",
      "☝️",
      "👍",
      "👎",
      "✊",
      "👊",
      "🤛",
      "🤜",
      "👏",
      "🙌",
      "👐",
      "🤲",
      "🤝",
      "🙏",
    ],
  },
  {
    name: "symbols",
    emojis: [
      "❤️",
      "🧡",
      "💛",
      "💚",
      "💙",
      "💜",
      "🖤",
      "🤍",
      "🤎",
      "💔",
      "❤️‍🔥",
      "❤️‍🩹",
      "💕",
      "💞",
      "💓",
      "💗",
      "💖",
      "💘",
      "💝",
      "💟",
      "☮️",
      "✝️",
      "☪️",
      "🕉",
      "☸️",
      "✡️",
      "🔯",
      "🕎",
      "☯️",
      "☦️",
      "🛐",
      "⛎",
      "♈",
      "♉",
      "♊",
      "♋",
      "♌",
      "♍",
      "♎",
      "♏",
      "♐",
      "♑",
      "♒",
      "♓",
      "🆔",
      "⚛️",
      "🉑",
      "☢️",
      "☣️",
      "📴",
      "📳",
      "🈶",
      "🈚",
      "🈸",
      "🈺",
      "🈷️",
      "✴️",
      "🆚",
      "💮",
      "🉐",
      "㊙️",
      "㊗️",
      "🈴",
      "🈵",
      "🈹",
      "🈲",
      "🅰️",
      "🅱️",
      "🆎",
      "🆑",
      "🅾️",
      "🆘",
      "❌",
      "⭕",
      "🛑",
      "⛔",
      "📛",
      "🚫",
      "💯",
      "💢",
      "♨️",
      "🚷",
      "🚯",
      "🚳",
      "🚱",
      "🔞",
      "📵",
      "🚭",
    ],
  },
  {
    name: "objects",
    emojis: [
      "⌚",
      "📱",
      "📲",
      "💻",
      "⌨️",
      "🖥️",
      "🖨️",
      "🖱️",
      "🖲️",
      "🕹️",
      "🗜️",
      "💽",
      "💾",
      "💿",
      "📀",
      "📼",
      "📷",
      "📸",
      "📹",
      "🎥",
      "📽️",
      "🎞️",
      "📞",
      "☎️",
      "📟",
      "📠",
      "📺",
      "📻",
      "🎙️",
      "🎚️",
      "🎛️",
      "🧭",
      "⏱️",
      "⏲️",
      "⏰",
      "🕰️",
      "⌛",
      "⏳",
      "📡",
      "🔋",
      "🔌",
      "💡",
      "🔦",
      "🕯️",
      "🪔",
      "🧯",
      "🛢️",
      "💸",
      "💵",
      "💴",
      "💶",
      "💷",
      "💰",
      "💳",
      "💎",
      "⚖️",
      "🧰",
      "🔧",
      "🔨",
      "⚒️",
      "🛠️",
      "⛏️",
      "🔩",
      "⚙️",
      "🧱",
      "⛓️",
      "🧲",
      "🔫",
      "💣",
      "🧨",
      "🪓",
      "🔪",
      "🗡️",
      "⚔️",
      "🛡️",
      "🚬",
      "⚰️",
      "⚱️",
      "🏺",
      "🔮",
      "📿",
      "🧿",
      "💈",
      "⚗️",
      "🔭",
      "🔬",
      "🕳️",
      "🩹",
      "🩺",
      "💊",
      "💉",
      "🩸",
      "🧬",
      "🦠",
      "🧫",
      "🧪",
      "🌡️",
      "🧹",
      "🧺",
      "🧻",
      "🚽",
      "🚰",
      "🚿",
      "🛁",
      "🧼",
      "🪒",
      "🧽",
      "🧴",
      "🛎️",
      "🔑",
      "🗝️",
      "🚪",
      "🪑",
      "🛋️",
      "🛏️",
      "🧸",
      "🖼️",
      "🛍️",
      "🛒",
      "🎁",
      "🎈",
      "🎏",
      "🎀",
      "🪄",
      "🪅",
      "🪆",
      "🎊",
      "🎉",
      "🎎",
      "🏮",
      "🎐",
      "🧧",
      "✉️",
      "📩",
      "📨",
      "📧",
      "💌",
      "📥",
      "📤",
      "📦",
      "🏷️",
      "📪",
      "📫",
      "📬",
      "📭",
      "📮",
      "📯",
      "📜",
      "📃",
      "📄",
      "📑",
      "🧾",
      "📊",
      "📈",
      "📉",
      "🗒️",
      "🗓️",
      "📆",
      "📅",
      "🗑️",
      "📇",
      "📋",
      "📁",
      "📂",
      "🗂️",
      "🗄️",
      "📚",
      "📓",
      "📔",
      "📒",
      "📕",
      "📗",
      "📘",
      "📙",
      "📎",
      "🖇️",
      "📏",
      "📐",
      "✂️",
      "🗃️",
      "🗳️",
      "🗄️",
    ],
  },
];

export const COUNTRY_CODES = [
  { name: "Afghanistan", dialCode: "+93", code: "AF", flag: "🇦🇫" },
  { name: "Albania", dialCode: "+355", code: "AL", flag: "🇦🇱" },
  { name: "Algeria", dialCode: "+213", code: "DZ", flag: "🇩🇿" },
  { name: "Argentina", dialCode: "+54", code: "AR", flag: "🇦🇷" },
  { name: "Australia", dialCode: "+61", code: "AU", flag: "🇦🇺" },
  { name: "Austria", dialCode: "+43", code: "AT", flag: "🇦🇹" },
  { name: "Bangladesh", dialCode: "+880", code: "BD", flag: "🇧🇩" },
  { name: "Belgium", dialCode: "+32", code: "BE", flag: "🇧🇪" },
  { name: "Brazil", dialCode: "+55", code: "BR", flag: "🇧🇷" },
  { name: "Canada", dialCode: "+1", code: "CA", flag: "🇨🇦" },
  { name: "China", dialCode: "+86", code: "CN", flag: "🇨🇳" },
  { name: "France", dialCode: "+33", code: "FR", flag: "🇫🇷" },
  { name: "Germany", dialCode: "+49", code: "DE", flag: "🇩🇪" },
  { name: "India", dialCode: "+91", code: "IN", flag: "🇮🇳" },
  { name: "Indonesia", dialCode: "+62", code: "ID", flag: "🇮🇩" },
  { name: "Italy", dialCode: "+39", code: "IT", flag: "🇮🇹" },
  { name: "Japan", dialCode: "+81", code: "JP", flag: "🇯🇵" },
  { name: "Malaysia", dialCode: "+60", code: "MY", flag: "🇲🇾" },
  { name: "Mexico", dialCode: "+52", code: "MX", flag: "🇲🇽" },
  { name: "Nepal", dialCode: "+977", code: "NP", flag: "🇳🇵" },
  { name: "Netherlands", dialCode: "+31", code: "NL", flag: "🇳🇱" },
  { name: "New Zealand", dialCode: "+64", code: "NZ", flag: "🇳🇿" },
  { name: "Nigeria", dialCode: "+234", code: "NG", flag: "🇳🇬" },
  { name: "Pakistan", dialCode: "+92", code: "PK", flag: "🇵🇰" },
  { name: "Philippines", dialCode: "+63", code: "PH", flag: "🇵🇭" },
  { name: "Russia", dialCode: "+7", code: "RU", flag: "🇷🇺" },
  { name: "Saudi Arabia", dialCode: "+966", code: "SA", flag: "🇸🇦" },
  { name: "Singapore", dialCode: "+65", code: "SG", flag: "🇸🇬" },
  { name: "South Africa", dialCode: "+27", code: "ZA", flag: "🇿🇦" },
  { name: "South Korea", dialCode: "+82", code: "KR", flag: "🇰🇷" },
  { name: "Spain", dialCode: "+34", code: "ES", flag: "🇪🇸" },
  { name: "Sri Lanka", dialCode: "+94", code: "LK", flag: "🇱🇰" },
  { name: "Sweden", dialCode: "+46", code: "SE", flag: "🇸🇪" },
  { name: "Switzerland", dialCode: "+41", code: "CH", flag: "🇨🇭" },
  { name: "Thailand", dialCode: "+66", code: "TH", flag: "🇹🇭" },
  { name: "Turkey", dialCode: "+90", code: "TR", flag: "🇹🇷" },
  { name: "UAE", dialCode: "+971", code: "AE", flag: "🇦🇪" },
  { name: "United Kingdom", dialCode: "+44", code: "GB", flag: "🇬🇧" },
  { name: "United States", dialCode: "+1", code: "US", flag: "🇺🇸" },
  { name: "Vietnam", dialCode: "+84", code: "VN", flag: "🇻🇳" },
];

export const INDIAN_BANKS = [
  "State Bank of India",
  "HDFC Bank",
  "ICICI Bank",
  "Axis Bank",
  "Kotak Mahindra Bank",
  "Bank of Baroda",
  "Punjab National Bank",
  "Canara Bank",
  "Union Bank of India",
  "Bank of India",
  "Indian Bank",
  "Central Bank of India",
  "Indian Overseas Bank",
  "UCO Bank",
  "Bank of Maharashtra",
  "Punjab & Sind Bank",
  "Yes Bank",
  "IDBI Bank",
  "IDFC FIRST Bank",
  "IndusInd Bank",
  "Federal Bank",
  "South Indian Bank",
  "Karur Vysya Bank",
  "City Union Bank",
  "Tamilnad Mercantile Bank",
  "Dhanlaxmi Bank",
  "Nainital Bank",
  "RBL Bank",
  "Bandhan Bank",
  "Jammu & Kashmir Bank",
  "Karnataka Bank",
  "Kerala Gramin Bank",
  "Saraswat Bank",
  "Abhyudaya Co-op Bank",
  "Ahmedabad Mercantile Co-op Bank",
  "Andhra Pradesh Grameena Vikas Bank",
  "Aryavart Bank",
  "Au Small Finance Bank",
  "Baroda Gujarat Gramin Bank",
  "Baroda Rajasthan Kshetriya Gramin Bank",
  "Baroda Uttar Pradesh Gramin Bank",
  "Chaitanya Godavari Grameena Bank",
  "Dakshin Bihar Gramin Bank",
  "Ellaquai Dehati Bank",
  "Equitas Small Finance Bank",
  "ESAF Small Finance Bank",
  "Fincare Small Finance Bank",
  "Himachal Pradesh Gramin Bank",
  "Jana Small Finance Bank",
  "Karnataka Vikas Grameena Bank",
  "Madhya Pradesh Gramin Bank",
  "Madhyanchal Gramin Bank",
  "Maharashtra Gramin Bank",
  "Manipur Rural Bank",
  "Meghalaya Rural Bank",
  "Mizoram Rural Bank",
  "Nagaland Rural Bank",
  "North East Small Finance Bank",
  "Odisha Gramya Bank",
  "Paschim Banga Gramin Bank",
  "Prathama UP Gramin Bank",
  "Puduvai Bharathiar Grama Bank",
  "Punjab Gramin Bank",
  "Rajasthan Marudhara Gramin Bank",
  "Saptagiri Grameena Bank",
  "Sarva Haryana Gramin Bank",
  "Saurashtra Gramin Bank",
  "Srei Equipment Finance",
  "Suryoday Small Finance Bank",
  "Telangana Grameena Bank",
  "Tripura Gramin Bank",
  "Utkal Grameen Bank",
  "Uttar Bihar Gramin Bank",
  "Uttarakhand Gramin Bank",
  "Vananchal Gramin Bank",
  "Vidharbha Konkan Gramin Bank",
].sort();

export const placeholderMap: any = {
  name: "Enter the name",
  email: "Enter the email",
  mobile: "Enter the mobile number",
  portal: "Enter the portal URL",
  domain: "Enter the domain name",
  ip: "Enter the IP address",
  message: "Enter the message",
  username: "Enter the username",
  password: "Enter the password",
  info: "Enter information",
  login_email: "Enter the login email",
};


export const COLORS = {

  // ── existing 6 ──────────────────────────────────────────────────────────

  blue: {
    label: 'Blue', swatchLight: '#2563eb', swatchDark: '#60a5fa',
    light: {
      '--color-primary': '#1d4ed8', '--color-primary-light': '#3b82f6',
      '--color-primary-dark': '#1e3a8a', '--color-secondary': '#bfdbfe',
      '--color-accent': '#2563eb', '--color-bg': '#eff6ff',
      '--color-surface': '#ffffff', '--color-font': '#0a1128',
      '--color-muted': '#1e3a8a', '--color-border': '#bfdbfe',
      '--color-hover': '#dbeafe', '--color-success': '#15803d',
      '--color-warning': '#ca8a04', '--color-danger': '#dc2626',
      '--color-info': '#0ea5e9', '--shadow-sm': '0 2px 6px rgba(29,78,216,0.14)',
      '--shadow-md': '0 8px 16px rgba(29,78,216,0.2)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
    dark: {
      '--color-primary': '#3b82f6', '--color-primary-light': '#93c5fd',
      '--color-primary-dark': '#1d4ed8', '--color-secondary': '#0a1f5c',
      '--color-accent': '#60a5fa', '--color-bg': '#020b18',
      '--color-surface': '#071028', '--color-font': '#eff6ff',
      '--color-muted': '#93c5fd', '--color-border': '#1e3a8a',
      '--color-hover': '#0f1f40', '--color-success': '#4ade80',
      '--color-warning': '#fbbf24', '--color-danger': '#f87171',
      '--color-info': '#38bdf8', '--shadow-sm': '0 2px 6px rgba(59,130,246,0.2)',
      '--shadow-md': '0 8px 16px rgba(59,130,246,0.3)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
  },

  red: {
    label: 'Red', swatchLight: '#ef4444', swatchDark: '#f87171',
    light: {
      '--color-primary': '#b91c1c', '--color-primary-light': '#ef4444',
      '--color-primary-dark': '#7f1d1d', '--color-secondary': '#fecaca',
      '--color-accent': '#dc2626', '--color-bg': '#fef2f2',
      '--color-surface': '#ffffff', '--color-font': '#1f0a0a',
      '--color-muted': '#7f1d1d', '--color-border': '#fecaca',
      '--color-hover': '#fee2e2', '--color-success': '#15803d',
      '--color-warning': '#ca8a04', '--color-danger': '#dc2626',
      '--color-info': '#0ea5e9', '--shadow-sm': '0 2px 6px rgba(185,28,28,0.14)',
      '--shadow-md': '0 8px 16px rgba(185,28,28,0.2)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
    dark: {
      '--color-primary': '#ef4444', '--color-primary-light': '#fca5a5',
      '--color-primary-dark': '#b91c1c', '--color-secondary': '#450a0a',
      '--color-accent': '#f87171', '--color-bg': '#0f0505',
      '--color-surface': '#1c0a0a', '--color-font': '#fef2f2',
      '--color-muted': '#fca5a5', '--color-border': '#7f1d1d',
      '--color-hover': '#2d0a0a', '--color-success': '#4ade80',
      '--color-warning': '#fbbf24', '--color-danger': '#f87171',
      '--color-info': '#38bdf8', '--shadow-sm': '0 2px 6px rgba(239,68,68,0.2)',
      '--shadow-md': '0 8px 16px rgba(239,68,68,0.3)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
  },

  green: {
    label: 'Green', swatchLight: '#16a34a', swatchDark: '#4ade80',
    light: {
      '--color-primary': '#15803d', '--color-primary-light': '#22c55e',
      '--color-primary-dark': '#14532d', '--color-secondary': '#bbf7d0',
      '--color-accent': '#16a34a', '--color-bg': '#f0fdf4',
      '--color-surface': '#ffffff', '--color-font': '#052e16',
      '--color-muted': '#14532d', '--color-border': '#bbf7d0',
      '--color-hover': '#dcfce7', '--color-success': '#15803d',
      '--color-warning': '#ca8a04', '--color-danger': '#dc2626',
      '--color-info': '#0ea5e9', '--shadow-sm': '0 2px 6px rgba(21,128,61,0.14)',
      '--shadow-md': '0 8px 16px rgba(21,128,61,0.2)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
    dark: {
      '--color-primary': '#22c55e', '--color-primary-light': '#86efac',
      '--color-primary-dark': '#15803d', '--color-secondary': '#052e16',
      '--color-accent': '#4ade80', '--color-bg': '#011008',
      '--color-surface': '#031a0e', '--color-font': '#f0fdf4',
      '--color-muted': '#86efac', '--color-border': '#14532d',
      '--color-hover': '#071f0f', '--color-success': '#4ade80',
      '--color-warning': '#fbbf24', '--color-danger': '#f87171',
      '--color-info': '#38bdf8', '--shadow-sm': '0 2px 6px rgba(34,197,94,0.2)',
      '--shadow-md': '0 8px 16px rgba(34,197,94,0.3)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
  },

  purple: {
    label: 'Purple', swatchLight: '#7c3aed', swatchDark: '#a78bfa',
    light: {
      '--color-primary': '#6d28d9', '--color-primary-light': '#8b5cf6',
      '--color-primary-dark': '#4c1d95', '--color-secondary': '#ddd6fe',
      '--color-accent': '#7c3aed', '--color-bg': '#f5f3ff',
      '--color-surface': '#ffffff', '--color-font': '#1e0a40',
      '--color-muted': '#4c1d95', '--color-border': '#ddd6fe',
      '--color-hover': '#ede9fe', '--color-success': '#15803d',
      '--color-warning': '#ca8a04', '--color-danger': '#dc2626',
      '--color-info': '#0ea5e9', '--shadow-sm': '0 2px 6px rgba(109,40,217,0.14)',
      '--shadow-md': '0 8px 16px rgba(109,40,217,0.2)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
    dark: {
      '--color-primary': '#8b5cf6', '--color-primary-light': '#c4b5fd',
      '--color-primary-dark': '#6d28d9', '--color-secondary': '#1e0a3c',
      '--color-accent': '#a78bfa', '--color-bg': '#0a0314',
      '--color-surface': '#12052a', '--color-font': '#f5f3ff',
      '--color-muted': '#c4b5fd', '--color-border': '#4c1d95',
      '--color-hover': '#1a0836', '--color-success': '#4ade80',
      '--color-warning': '#fbbf24', '--color-danger': '#f87171',
      '--color-info': '#38bdf8', '--shadow-sm': '0 2px 6px rgba(139,92,246,0.2)',
      '--shadow-md': '0 8px 16px rgba(139,92,246,0.3)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
  },

  orange: {
    label: 'Orange', swatchLight: '#ea580c', swatchDark: '#fb923c',
    light: {
      '--color-primary': '#c2410c', '--color-primary-light': '#f97316',
      '--color-primary-dark': '#7c2d12', '--color-secondary': '#fed7aa',
      '--color-accent': '#ea580c', '--color-bg': '#fff7ed',
      '--color-surface': '#ffffff', '--color-font': '#1f0a02',
      '--color-muted': '#7c2d12', '--color-border': '#fed7aa',
      '--color-hover': '#ffedd5', '--color-success': '#15803d',
      '--color-warning': '#ca8a04', '--color-danger': '#dc2626',
      '--color-info': '#0ea5e9', '--shadow-sm': '0 2px 6px rgba(194,65,12,0.14)',
      '--shadow-md': '0 8px 16px rgba(194,65,12,0.2)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
    dark: {
      '--color-primary': '#f97316', '--color-primary-light': '#fdba74',
      '--color-primary-dark': '#c2410c', '--color-secondary': '#431407',
      '--color-accent': '#fb923c', '--color-bg': '#120500',
      '--color-surface': '#1e0c02', '--color-font': '#fff7ed',
      '--color-muted': '#fdba74', '--color-border': '#7c2d12',
      '--color-hover': '#2d0f04', '--color-success': '#4ade80',
      '--color-warning': '#fbbf24', '--color-danger': '#f87171',
      '--color-info': '#38bdf8', '--shadow-sm': '0 2px 6px rgba(249,115,22,0.2)',
      '--shadow-md': '0 8px 16px rgba(249,115,22,0.3)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
  },

  teal: {
    label: 'Teal', swatchLight: '#0d9488', swatchDark: '#2dd4bf',
    light: {
      '--color-primary': '#0f766e', '--color-primary-light': '#14b8a6',
      '--color-primary-dark': '#134e4a', '--color-secondary': '#99f6e4',
      '--color-accent': '#0d9488', '--color-bg': '#f0fdfa',
      '--color-surface': '#ffffff', '--color-font': '#021a17',
      '--color-muted': '#134e4a', '--color-border': '#99f6e4',
      '--color-hover': '#ccfbf1', '--color-success': '#15803d',
      '--color-warning': '#ca8a04', '--color-danger': '#dc2626',
      '--color-info': '#0ea5e9', '--shadow-sm': '0 2px 6px rgba(15,118,110,0.14)',
      '--shadow-md': '0 8px 16px rgba(15,118,110,0.2)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
    dark: {
      '--color-primary': '#14b8a6', '--color-primary-light': '#5eead4',
      '--color-primary-dark': '#0f766e', '--color-secondary': '#021a17',
      '--color-accent': '#2dd4bf', '--color-bg': '#010f0e',
      '--color-surface': '#031614', '--color-font': '#f0fdfa',
      '--color-muted': '#5eead4', '--color-border': '#134e4a',
      '--color-hover': '#071f1e', '--color-success': '#4ade80',
      '--color-warning': '#fbbf24', '--color-danger': '#f87171',
      '--color-info': '#38bdf8', '--shadow-sm': '0 2px 6px rgba(20,184,166,0.2)',
      '--shadow-md': '0 8px 16px rgba(20,184,166,0.3)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
  },

  // ── 6 new professional palettes ─────────────────────────────────────────

  // Sophisticated rose — great for dark mode, warm & elegant
  rose: {
    label: 'Rose', swatchLight: '#e11d48', swatchDark: '#fb7185',
    light: {
      '--color-primary': '#be123c', '--color-primary-light': '#f43f5e',
      '--color-primary-dark': '#881337', '--color-secondary': '#fecdd3',
      '--color-accent': '#e11d48', '--color-bg': '#fff1f2',
      '--color-surface': '#ffffff', '--color-font': '#1f0614',
      '--color-muted': '#881337', '--color-border': '#fecdd3',
      '--color-hover': '#ffe4e6', '--color-success': '#15803d',
      '--color-warning': '#ca8a04', '--color-danger': '#e11d48',
      '--color-info': '#0ea5e9', '--shadow-sm': '0 2px 6px rgba(190,18,60,0.14)',
      '--shadow-md': '0 8px 16px rgba(190,18,60,0.2)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
    dark: {
      '--color-primary': '#f43f5e', '--color-primary-light': '#fda4af',
      '--color-primary-dark': '#be123c', '--color-secondary': '#3b0017',
      '--color-accent': '#fb7185', '--color-bg': '#100208',
      '--color-surface': '#1e0510', '--color-font': '#fff1f2',
      '--color-muted': '#fda4af', '--color-border': '#881337',
      '--color-hover': '#2d0618', '--color-success': '#4ade80',
      '--color-warning': '#fbbf24', '--color-danger': '#fb7185',
      '--color-info': '#38bdf8', '--shadow-sm': '0 2px 6px rgba(244,63,94,0.22)',
      '--shadow-md': '0 8px 20px rgba(244,63,94,0.32)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
  },

  // Deep indigo — professional, SaaS-grade, excellent dark mode
  indigo: {
    label: 'Indigo', swatchLight: '#4338ca', swatchDark: '#818cf8',
    light: {
      '--color-primary': '#3730a3', '--color-primary-light': '#6366f1',
      '--color-primary-dark': '#312e81', '--color-secondary': '#c7d2fe',
      '--color-accent': '#4338ca', '--color-bg': '#eef2ff',
      '--color-surface': '#ffffff', '--color-font': '#0d0c2b',
      '--color-muted': '#312e81', '--color-border': '#c7d2fe',
      '--color-hover': '#e0e7ff', '--color-success': '#15803d',
      '--color-warning': '#ca8a04', '--color-danger': '#dc2626',
      '--color-info': '#0ea5e9', '--shadow-sm': '0 2px 6px rgba(55,48,163,0.14)',
      '--shadow-md': '0 8px 16px rgba(55,48,163,0.2)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
    dark: {
      '--color-primary': '#6366f1', '--color-primary-light': '#a5b4fc',
      '--color-primary-dark': '#3730a3', '--color-secondary': '#160f3d',
      '--color-accent': '#818cf8', '--color-bg': '#06050f',
      '--color-surface': '#0e0c24', '--color-font': '#eef2ff',
      '--color-muted': '#a5b4fc', '--color-border': '#312e81',
      '--color-hover': '#151130', '--color-success': '#4ade80',
      '--color-warning': '#fbbf24', '--color-danger': '#f87171',
      '--color-info': '#38bdf8', '--shadow-sm': '0 2px 6px rgba(99,102,241,0.22)',
      '--shadow-md': '0 8px 20px rgba(99,102,241,0.32)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
  },

  // Warm amber — dashboard-friendly, finance/analytics feel
  amber: {
    label: 'Amber', swatchLight: '#d97706', swatchDark: '#fbbf24',
    light: {
      '--color-primary': '#b45309', '--color-primary-light': '#f59e0b',
      '--color-primary-dark': '#78350f', '--color-secondary': '#fde68a',
      '--color-accent': '#d97706', '--color-bg': '#fffbeb',
      '--color-surface': '#ffffff', '--color-font': '#1c0f00',
      '--color-muted': '#78350f', '--color-border': '#fde68a',
      '--color-hover': '#fef3c7', '--color-success': '#15803d',
      '--color-warning': '#d97706', '--color-danger': '#dc2626',
      '--color-info': '#0ea5e9', '--shadow-sm': '0 2px 6px rgba(180,83,9,0.14)',
      '--shadow-md': '0 8px 16px rgba(180,83,9,0.2)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
    dark: {
      '--color-primary': '#f59e0b', '--color-primary-light': '#fcd34d',
      '--color-primary-dark': '#b45309', '--color-secondary': '#3d1f00',
      '--color-accent': '#fbbf24', '--color-bg': '#110900',
      '--color-surface': '#1c1000', '--color-font': '#fffbeb',
      '--color-muted': '#fcd34d', '--color-border': '#78350f',
      '--color-hover': '#2a1600', '--color-success': '#4ade80',
      '--color-warning': '#fbbf24', '--color-danger': '#f87171',
      '--color-info': '#38bdf8', '--shadow-sm': '0 2px 6px rgba(245,158,11,0.22)',
      '--shadow-md': '0 8px 20px rgba(245,158,11,0.32)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
  },

  // Electric cyan — perfect for dark-mode-first apps, techy/developer feel
  cyan: {
    label: 'Cyan', swatchLight: '#0891b2', swatchDark: '#22d3ee',
    light: {
      '--color-primary': '#0e7490', '--color-primary-light': '#06b6d4',
      '--color-primary-dark': '#164e63', '--color-secondary': '#a5f3fc',
      '--color-accent': '#0891b2', '--color-bg': '#ecfeff',
      '--color-surface': '#ffffff', '--color-font': '#061820',
      '--color-muted': '#164e63', '--color-border': '#a5f3fc',
      '--color-hover': '#cffafe', '--color-success': '#15803d',
      '--color-warning': '#ca8a04', '--color-danger': '#dc2626',
      '--color-info': '#06b6d4', '--shadow-sm': '0 2px 6px rgba(14,116,144,0.14)',
      '--shadow-md': '0 8px 16px rgba(14,116,144,0.2)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
    dark: {
      '--color-primary': '#06b6d4', '--color-primary-light': '#67e8f9',
      '--color-primary-dark': '#0e7490', '--color-secondary': '#021e26',
      '--color-accent': '#22d3ee', '--color-bg': '#010d10',
      '--color-surface': '#03181e', '--color-font': '#ecfeff',
      '--color-muted': '#67e8f9', '--color-border': '#164e63',
      '--color-hover': '#052430', '--color-success': '#4ade80',
      '--color-warning': '#fbbf24', '--color-danger': '#f87171',
      '--color-info': '#22d3ee', '--shadow-sm': '0 2px 6px rgba(6,182,212,0.22)',
      '--shadow-md': '0 8px 20px rgba(6,182,212,0.35)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
  },

  // Neutral slate — ultra-professional, minimal, enterprise grade
  slate: {
    label: 'Slate', swatchLight: '#475569', swatchDark: '#94a3b8',
    light: {
      '--color-primary': '#334155', '--color-primary-light': '#64748b',
      '--color-primary-dark': '#0f172a', '--color-secondary': '#e2e8f0',
      '--color-accent': '#475569', '--color-bg': '#f8fafc',
      '--color-surface': '#ffffff', '--color-font': '#0f172a',
      '--color-muted': '#64748b', '--color-border': '#e2e8f0',
      '--color-hover': '#f1f5f9', '--color-success': '#15803d',
      '--color-warning': '#ca8a04', '--color-danger': '#dc2626',
      '--color-info': '#0ea5e9', '--shadow-sm': '0 2px 6px rgba(51,65,85,0.1)',
      '--shadow-md': '0 8px 16px rgba(51,65,85,0.15)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
    dark: {
      '--color-primary': '#94a3b8', '--color-primary-light': '#cbd5e1',
      '--color-primary-dark': '#64748b', '--color-secondary': '#0d1424',
      '--color-accent': '#94a3b8', '--color-bg': '#020408',
      '--color-surface': '#0d1117', '--color-font': '#f1f5f9',
      '--color-muted': '#94a3b8', '--color-border': '#1e293b',
      '--color-hover': '#161d2a', '--color-success': '#4ade80',
      '--color-warning': '#fbbf24', '--color-danger': '#f87171',
      '--color-info': '#38bdf8', '--shadow-sm': '0 2px 6px rgba(0,0,0,0.3)',
      '--shadow-md': '0 8px 20px rgba(0,0,0,0.45)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
  },

  // Rich violet — modern, creative tools, dark-mode stunning
  violet: {
    label: 'Violet', swatchLight: '#7c3aed', swatchDark: '#c084fc',
    light: {
      '--color-primary': '#6d28d9', '--color-primary-light': '#a855f7',
      '--color-primary-dark': '#4a1d96', '--color-secondary': '#f3e8ff',
      '--color-accent': '#7c3aed', '--color-bg': '#faf5ff',
      '--color-surface': '#ffffff', '--color-font': '#1a0533',
      '--color-muted': '#6b21a8', '--color-border': '#e9d5ff',
      '--color-hover': '#f3e8ff', '--color-success': '#15803d',
      '--color-warning': '#ca8a04', '--color-danger': '#dc2626',
      '--color-info': '#0ea5e9', '--shadow-sm': '0 2px 6px rgba(109,40,217,0.14)',
      '--shadow-md': '0 8px 16px rgba(109,40,217,0.22)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
    dark: {
      '--color-primary': '#a855f7', '--color-primary-light': '#d8b4fe',
      '--color-primary-dark': '#7e22ce', '--color-secondary': '#1e0540',
      '--color-accent': '#c084fc', '--color-bg': '#08021a',
      '--color-surface': '#110530', '--color-font': '#faf5ff',
      '--color-muted': '#d8b4fe', '--color-border': '#4a1d96',
      '--color-hover': '#1a083d', '--color-success': '#4ade80',
      '--color-warning': '#fbbf24', '--color-danger': '#f87171',
      '--color-info': '#38bdf8', '--shadow-sm': '0 2px 6px rgba(168,85,247,0.25)',
      '--shadow-md': '0 8px 20px rgba(168,85,247,0.38)',
      '--radius-md': '0.5rem', '--radius-lg': '0.75rem',
    },
  },

};